import type { Metadata } from 'next'
import './styles/globals.scss'
import SWRConfigContext from './context/SWRConfigContext'
import { Suspense } from 'react'
import Loading from '@/loading'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body
        className="bg-[--primary-color] flex min-h-screen flex-col"
        suppressHydrationWarning={true}
      >
        <div id="portal"></div>
        <Suspense fallback={<Loading />}>
          <SWRConfigContext>{children}</SWRConfigContext>
        </Suspense>
      </body>
    </html>
  )
}
