import type { Metadata } from 'next'

import { Inter } from 'next/font/google'

import './globals.scss'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const mode = cookies().get('mode')

  return (
    <html lang='ko' className={mode?.value === 'light' ? '' : 'dark-mode'}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
